### ISSUE TITLE
Settings of Tileserver-php

### ISSUE THREAD

**Issue by PaulJurich** [klokantech/tileserver-php#103] opened 2017-04-24 07:29 UTC
I apologize for my poor English, but would like to ask for advice in setting up your product.
When you type the following in the address bar of the browser:
http: //<ipadress>/tileserver/tileserver.php?service=wmts&request=getcapabilities&version=1.0.0
service returns me the answer:
wmts&reguest ([]);
Please explain to me that I'm doing wrong, maybe additional settings are required?
Also I ask to explain, in what directory in relation to the file tileserver.php should I place the cache of tiles?

**Comment by daliborjanak** [comment] 2017-04-24 07:39
Can you provide us a link to this page? Are you requesting get capabilities XML? You have wrong parameters in the query. If you need WMTS get capabilities use short /wmts/ link. This is better. If you are requesting getTIle you have to specify which tile you need in a query.

**Comment by PaulJurich** [comment] 2017-04-24 08:25
Unfortunately, the service is deployed in a segment of the network that does not have an Internet connection.
Can you give an example of a correct query using a short /wmts/ link?

**Comment by daliborjanak** [comment] 2017-04-24 08:35
http://labs.klokantech.com/tileserver-php/wmts

**Comment by PaulJurich** [comment] 2017-04-24 08:56
Excellent! It worked!
Can you provide an example of a valid wmts-tile request?

**Comment by daliborjanak** [comment] 2017-04-24 09:14
Schema: http://labs.klokantech.com/tileserver-php/geography-class/{TileMatrix}/{TileCol}/{TileRow}.jpg
E.g: http://labs.klokantech.com/tileserver-php/geography-class/2/2/1.jpg
This is RESTfull schema.

**Comment by PaulJurich** [comment] 2017-04-24 10:51
I correctly understand that the structure of files and folders should be as follows:
/var/www/tileserver-php/tileserver.php
/var/www/tileserver-php/tilefolder/1..n/1..n/n.jpg
I'm right?

**Comment by PaulJurich** [comment] 2017-04-24 12:45
Can you put here an example of a query in the format of a kvp?
Thanks in advance.

**Comment by daliborjanak** [comment] 2017-04-25 16:20
Tileserver is supporting fully WMTS. All requests are defined in documents by OGC here:
http://www.opengeospatial.org/standards/wmts

This is not a bug or issue. I'm closing.

**Closed by daliborjanak** 2017-04-25 16:20 UTC
