### ISSUE TITLE
Tifinagh font is not supported ?

### ISSUE THREAD

**Issue by nouryf** [klokantech/tileserver-php#77] opened 2016-04-03 15:07 UTC
Hi,

I used the mbtiles available here: https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v1.0/extracts/morocco.mbtiles

Some POI have in their name 'Tifinagh' language. If zoomed in enough to start seeing cities and town, some of them will have their label displayed in 'French Tifinagh and Arabic'. The tifinagh part is displayed as squares. I assume Tifinagh font may not be supported here ?

I used the OSM bright style: https://github.com/mapbox/mapbox-studio-osm-bright.tm2

Thanks

**Comment by klokan** [comment] 2016-04-04 07:28
TileServer serves vector .pbf map tiles. Fonts are served by your application. You can use any font you want with MapBox GL JS - if you serve it correctly as glyphs. https://github.com/klokantech/osm2vectortiles-gl-styles

We can assist you with the setup of your map styles with custom fonts as part of one-to-one commercial support. Please use: https://sites.fastspring.com/klokantech/instant/support

This is not a bug of TileServer-PHP. Closing.

**Closed by klokan** 2016-04-04 07:28 UTC
