### ISSUE TITLE
unexpected token _

### ISSUE THREAD

**Issue by heaversm** [klokantech/tileserver-php#57] opened 2015-10-28 19:43 UTC
Hi - I'm using tileserver with an uncustomized mapbox example and getting the error:

```
Uncaught SyntaxError: Unexpected token _
<img width="1637" alt="screen shot 2015-10-28 at 3 40 21 pm" src="https://cloud.githubusercontent.com/assets/520541/10800822/6648c6dc-7d8a-11e5-9dae-b346bb651d18.png">

```

Basically all I've done is download tileserver, serve it on a local MAMP server, drop an .mbtile file exported from tilemill into the tileserver directory, and load up tileserver.php, and click on the "preview" link under mapbox.

<img width="1637" alt="screen shot 2015-10-28 at 3 40 21 pm" src="https://cloud.githubusercontent.com/assets/520541/10800859/9a93142e-7d8a-11e5-8b7c-26b16f057b26.png">
See attached image.

**Comment by daliborjanak** [comment] 2016-02-01 19:56
Could you please provide us data or more information? We couldn't reproduce it from your bug report

**Comment by klokan** [comment] 2016-03-02 12:54
No answer from @heaversm. Closing.

**Closed by klokan** 2016-03-02 12:54 UTC
