### ISSUE TITLE
Missing cover and google maps error

### ISSUE THREAD

**Issue by idanka** [klokantech/tileserver-php#102] opened 2017-04-16 09:42 UTC
1. Missing cover and google maps error.
2. Google map works on your own machine.

Google maps error server
[error](https://www.valkoi-konyvtar.tk/wp-content/uploads/2017/04/www.valkoi-konyvtar.tk-kepernyofoto-2017-04-16-10.38.16.png)

My pc works 1
[my pc1](https://www.valkoi-konyvtar.tk/wp-content/uploads/2017/04/www.valkoi-konyvtar.tk-kepernyofoto-2017-04-16-10.38.57.png)

My pc works 2
[my pc2](https://www.valkoi-konyvtar.tk/wp-content/uploads/2017/04/www.valkoi-konyvtar.tk-kepernyofoto-2017-04-16-10.38.40.png)

MapTiler Settings
[settings](https://www.valkoi-konyvtar.tk/wp-content/uploads/2017/04/www.valkoi-konyvtar.tk-kepernyofoto-2017-04-16-11.36.45.png)

Server missing cover
[cover missing](https://www.valkoi-konyvtar.tk/wp-content/uploads/2017/04/www.valkoi-konyvtar.tk-kepernyofoto-2017-04-16-10.37.40.png)

What is wrong can be improved?
_Sorry Googe translate._

**Comment by idanka** [comment] 2017-04-16 13:31
Howto add "html" dns preload? Sample:
<link rel="dns-prefetch" href="//tileserver-idstudio.tk">
<link rel="dns-prefetch" href="//a.tileserver-idstudio.tk">
<link rel="dns-prefetch" href="//b.tileserver-idstudio.tk">
<link rel="dns-prefetch" href="//c.tileserver-idstudio.tk">

**Comment by daliborjanak** [comment] 2017-04-24 07:28
MapTiler couldn't add the key to tileserver. Maptiler uses Google maps key only with Cloudpush utility. You have to create viewer with your own code. On https://tileserver-idstudio.tk/#1862_v6/gmapsmaptiler.code , you can see a commented line with YOUR_API_KEY. Copy this page to index.html and include file on https://github.com/klokantech/tileserver-php/blob/master/tileserver.php#L14

You can enable support to more DNS on
https://github.com/klokantech/tileserver-php/blob/master/tileserver.php#L15

**Comment by idanka** [comment] 2017-04-25 15:56
Thanks for the help, 
DNS config ok and work.
But  template.php, I do not understand.
- where  to go?
- what is the content?
- Maybe  an example (template.php)

**Comment by daliborjanak** [comment] 2017-04-25 16:14
See at https://github.com/klokantech/tileserver-php/issues/31. There is a link to the wiki with description.

This is not a bug and other action. I'm closing

**Closed by daliborjanak** 2017-04-25 16:14 UTC
