### ISSUE TITLE
Google Maps Api Transparency slider not working

### ISSUE THREAD

**Issue by zulkifil** [klokantech/tileserver-php#120] opened 2018-02-19 09:58 UTC
Google Maps API (KlokanTech) transparency slider is not working perfectly. Sometime transparency do not work and also reset transparency when zooming & panning. Working fine with The release version & The frozen version if you mention version in code. It is not working in latest api version, Google map api has changed so need to tweak according to new google map api parameters.

**Comment by daliborjanak** [comment] 2018-02-19 11:44
Fixed now. Caused by new version of google maps API

**Closed by daliborjanak** 2018-02-19 11:44 UTC

**Comment by zulkifil** [comment] 2018-02-20 04:57
I am still having problem. i have html pages with source code of google map api klokantech. How to rectify this?


________________________________

**Comment by daliborjanak** [comment] 2018-02-20 07:39
Use an older version of google maps API:
``` html
    <script src="https://maps.google.com/maps/api/js?v=3.7&sensor=false"></script>
```
